import {
  User,
  InspectorProfile,
  Site,
  Inspection,
  Defect,
  CorrectiveAction,
  AppNotification,
  AuditLog,
  DashboardMetrics,
  IoTSensorNode,
  DecisionSupportItem,
  InspectionReportSummary,
} from './types';

export const DEMO_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'vishnu prasath',
    email: 'rajesh.inspector@sih.gov.in',
    role: 'INSPECTOR',
    inspectorId: 'INSP-BLR-101',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98450 12345',
    department: 'Civil Infrastructure Audit Wing',
  },
  {
    id: 'usr-2',
    name: 'maha',
    email: 'priya.supervisor@sih.gov.in',
    role: 'SUPERVISOR',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98201 54321',
    department: 'Quality Assurance & Safety Board',
  },
  {
    id: 'usr-3',
    name: 'vishnu',
    email: 'anand.director@sih.gov.in',
    role: 'DIRECTOR',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+91 99000 88888',
    department: 'Directorate of Infrastructure Safety',
  },
  {
    id: 'usr-4',
    name: 'siva',
    email: 'vikram.admin@sih.gov.in',
    role: 'ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    phone: '+91 97111 22233',
    department: 'Central Monitoring System Operations',
  },
];

export const DEMO_INSPECTORS: InspectorProfile[] = [
  {
    id: 'insp-1',
    inspectorId: 'INSP-BLR-101',
    name: 'Rajesh Kumar',
    email: 'rajesh.inspector@sih.gov.in',
    phone: '+91 98450 12345',
    badgeNumber: 'BDG-KA-778',
    zone: 'South Zone - Karnataka & TN',
    assignedSiteIds: ['site-1', 'site-3'],
    totalInspections: 84,
    qualityRating: 4.9,
    currentStatus: 'INSPECTING',
    currentLocation: {
      latitude: 12.9716,
      longitude: 77.5946,
      accuracy: 3.2,
      lastUpdated: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    },
  },
  {
    id: 'insp-2',
    inspectorId: 'INSP-DEL-102',
    name: 'Amit Patel',
    email: 'amit.patel@sih.gov.in',
    phone: '+91 98100 23456',
    badgeNumber: 'BDG-DL-412',
    zone: 'North Zone - NCR & Haryana',
    assignedSiteIds: ['site-2'],
    totalInspections: 62,
    qualityRating: 4.7,
    currentStatus: 'ON_DUTY',
    currentLocation: {
      latitude: 28.5355,
      longitude: 77.391,
      accuracy: 4.1,
      lastUpdated: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
  },
  {
    id: 'insp-3',
    inspectorId: 'INSP-HYD-103',
    name: 'Sneha Reddy',
    email: 'sneha.reddy@sih.gov.in',
    phone: '+91 98490 34567',
    badgeNumber: 'BDG-TG-621',
    zone: 'Central Zone - Telangana',
    assignedSiteIds: ['site-3'],
    totalInspections: 91,
    qualityRating: 4.95,
    currentStatus: 'INSPECTING',
    currentLocation: {
      latitude: 17.385,
      longitude: 78.4867,
      accuracy: 2.8,
      lastUpdated: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    },
  },
  {
    id: 'insp-4',
    inspectorId: 'INSP-PUN-104',
    name: 'Manoj Joshi',
    email: 'manoj.joshi@sih.gov.in',
    phone: '+91 98220 45678',
    badgeNumber: 'BDG-MH-339',
    zone: 'West Zone - Maharashtra',
    assignedSiteIds: ['site-4'],
    totalInspections: 53,
    qualityRating: 4.6,
    currentStatus: 'OFF_DUTY',
    currentLocation: {
      latitude: 18.5204,
      longitude: 73.8567,
      accuracy: 5.0,
      lastUpdated: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    },
  },
  {
    id: 'insp-5',
    inspectorId: 'INSP-MUM-105',
    name: 'Neha Chawla',
    email: 'neha.chawla@sih.gov.in',
    phone: '+91 98200 56789',
    badgeNumber: 'BDG-MH-890',
    zone: 'West Zone - Mumbai Metro',
    assignedSiteIds: ['site-5'],
    totalInspections: 78,
    qualityRating: 4.85,
    currentStatus: 'ON_DUTY',
    currentLocation: {
      latitude: 19.076,
      longitude: 72.8777,
      accuracy: 3.5,
      lastUpdated: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    },
  },
];

export const DEMO_SITES: Site[] = [
  {
    id: 'site-1',
    code: 'SITE-BLR-METRO-02',
    name: 'Metro Corridor Phase 2 - Elevated Viaduct',
    type: 'METRO',
    locationName: 'MG Road to Indiranagar Corridor, Bengaluru',
    latitude: 12.9756,
    longitude: 77.6094,
    geofenceRadiusMeters: 300,
    supervisorName: 'Priya Sharma',
    supervisorId: 'usr-2',
    healthScore: 78,
    activeDefectsCount: 3,
    criticalDefectsCount: 1,
  },
  {
    id: 'site-2',
    code: 'SITE-NCR-NH44-FLY',
    name: 'National Highway Overpass 44 Viaduct',
    type: 'HIGHWAY',
    locationName: 'Delhi-Agra Expressway Junction, NCR',
    latitude: 28.5355,
    longitude: 77.391,
    geofenceRadiusMeters: 450,
    supervisorName: 'Priya Sharma',
    supervisorId: 'usr-2',
    healthScore: 92,
    activeDefectsCount: 1,
    criticalDefectsCount: 0,
  },
  {
    id: 'site-3',
    code: 'SITE-HYD-TECH-ELEC',
    name: 'High Voltage Tech Park Substation 220kV',
    type: 'ENERGY',
    locationName: 'HITEC City Phase 3, Hyderabad',
    latitude: 17.4435,
    longitude: 78.3772,
    geofenceRadiusMeters: 250,
    supervisorName: 'Kavita Rao',
    supervisorId: 'usr-2',
    healthScore: 65,
    activeDefectsCount: 4,
    criticalDefectsCount: 2,
  },
  {
    id: 'site-4',
    code: 'SITE-PUN-WATER-TREAT',
    name: 'Green Valley Water Treatment Plant',
    type: 'WATER',
    locationName: 'Khadakwasla Basin, Pune',
    latitude: 18.4386,
    longitude: 73.7631,
    geofenceRadiusMeters: 350,
    supervisorName: 'Priya Sharma',
    supervisorId: 'usr-2',
    healthScore: 88,
    activeDefectsCount: 2,
    criticalDefectsCount: 0,
  },
  {
    id: 'site-5',
    code: 'SITE-MUM-TRANSIT-HUB',
    name: 'Smart City Multi-Modal Transit Terminal',
    type: 'INFRASTRUCTURE',
    locationName: 'Bandra-Kurla Complex Transit Node, Mumbai',
    latitude: 19.0657,
    longitude: 72.8688,
    geofenceRadiusMeters: 400,
    supervisorName: 'Priya Sharma',
    supervisorId: 'usr-2',
    healthScore: 71,
    activeDefectsCount: 5,
    criticalDefectsCount: 1,
  },
];

export const DEMO_DEFECTS: Defect[] = [
  {
    id: 'def-1',
    code: 'DEF-2026-001',
    inspectionId: 'insp-rec-1',
    siteId: 'site-1',
    siteName: 'Metro Corridor Phase 2 - Elevated Viaduct',
    inspectorId: 'INSP-BLR-101',
    inspectorName: 'Rajesh Kumar',
    title: 'Pier P-14 Cantilever Shear Crack & Concrete Spalling',
    description: 'Noticeable 4.2mm structural diagonal shear crack observed along Pier P-14 cantilever support arm. Rebar exposed with minor oxidization rust runoff onto safety net.',
    severity: 'CRITICAL',
    category: 'STRUCTURAL',
    status: 'IN_PROGRESS',
    detectedAt: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
    slaDeadline: new Date(Date.now() + 2 * 3600 * 1000).toISOString(), // 4h SLA for critical
    slaHours: 4,
    isEscalated: true,
    escalatedTo: 'DIRECTOR',
    latitude: 12.9758,
    longitude: 77.6091,
    evidencePhotos: [
      {
        id: 'ev-1',
        inspectionId: 'insp-rec-1',
        photoUrl: 'https://images.unsplash.com/photo-1590069261209-f8e9b8642343?w=600&auto=format&fit=crop&q=80',
        caption: 'Cantilever arm shear crack with exposed rebar at pier P-14',
        latitude: 12.9758,
        longitude: 77.6091,
        timestamp: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
        inspectorId: 'INSP-BLR-101',
        sha256Hash: 'a8b94f1c93847e19da82137bc89d41289fe9432ab127d498302bf784a9182301',
        isGeoTagged: true,
        type: 'DEFECT',
      },
    ],
    aiAnalysis: {
      detectedDefectType: 'Structural Shear Fracture & Rebar Corrosion',
      confidenceScore: 0.96,
      riskScore: 92,
      recommendedAction: 'Immediate structural jacketing, load mitigation, and ultrasonic velocity pulse testing.',
    },
    assignedTo: {
      userId: 'eng-101',
      name: 'Suresh Patil',
      team: 'Heavy Civil Rapid Response Unit',
      assignedAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
      deadline: new Date(Date.now() + 4 * 3600 * 1000).toISOString(),
    },
    correctiveAction: {
      id: 'ca-1',
      defectId: 'def-1',
      defectCode: 'DEF-2026-001',
      status: 'IN_PROGRESS',
      assignedToName: 'Suresh Patil',
      assignedTeam: 'Heavy Civil Rapid Response Unit',
      assignedAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
      deadline: new Date(Date.now() + 4 * 3600 * 1000).toISOString(),
      actionPlan: 'Erect temporary steel shoring prop, epoxy pressure injection into shear fissure, and apply carbon fiber polymer reinforcement wrap.',
      workLogs: [
        {
          timestamp: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
          author: 'Suresh Patil',
          note: 'Shoring towers mobilized to span 14. Crack depth gauged at 48mm.',
        },
        {
          timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
          author: 'Suresh Patil',
          note: 'First stage epoxy grouting underway. Surface sealed with primer.',
        },
      ],
      beforePhotoUrl: 'https://images.unsplash.com/photo-1590069261209-f8e9b8642343?w=600&auto=format&fit=crop&q=80',
    },
  },
  {
    id: 'def-2',
    code: 'DEF-2026-002',
    inspectionId: 'insp-rec-3',
    siteId: 'site-3',
    siteName: 'High Voltage Tech Park Substation 220kV',
    inspectorId: 'INSP-HYD-103',
    inspectorName: 'Sneha Reddy',
    title: 'Transformer Bay 2 Oil Leakage & Faulty Earth Pit Resistance',
    description: 'Transformer 2 radiator flange gasket compromised with active synthetic ester oil dripping. Earth pit #4 resistance measured 8.4 Ohms (Maximum allowed: 1.0 Ohm). High flashover hazard.',
    severity: 'CRITICAL',
    category: 'ELECTRICAL',
    status: 'DETECTED',
    detectedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    slaDeadline: new Date(Date.now() + 2 * 3600 * 1000).toISOString(),
    slaHours: 4,
    isEscalated: true,
    escalatedTo: 'DIRECTOR',
    latitude: 17.4439,
    longitude: 78.3775,
    evidencePhotos: [
      {
        id: 'ev-2',
        inspectionId: 'insp-rec-3',
        photoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
        caption: 'Active insulating oil pool below transformer radiator cooling fin',
        latitude: 17.4439,
        longitude: 78.3775,
        timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
        inspectorId: 'INSP-HYD-103',
        sha256Hash: '5e7a9b0c82f913d07e6b8294a5c317f2e4b0918a7c2b3d4e5f6a7b8c9d0e1f2a',
        isGeoTagged: true,
        type: 'DEFECT',
      },
    ],
    aiAnalysis: {
      detectedDefectType: 'Dielectric Oil Seepage & High Voltage Arc Risk',
      confidenceScore: 0.94,
      riskScore: 95,
      recommendedAction: 'Isolate Transformer Bay 2, drain radiator header, replace neoprene gasket, and treat earth pit with bentonite compound.',
    },
  },
  {
    id: 'def-3',
    code: 'DEF-2026-003',
    inspectionId: 'insp-rec-5',
    siteId: 'site-5',
    siteName: 'Smart City Multi-Modal Transit Terminal',
    inspectorId: 'INSP-MUM-105',
    inspectorName: 'Neha Chawla',
    title: 'Perimeter Escalator Emergency Stop Switch Non-Responsive',
    description: 'During safety sequence audit, E-Stop relay on Escalator ESC-03 failed to trip brake within required 250ms threshold. Mechanical friction brake pads worn below 2mm.',
    severity: 'HIGH',
    category: 'SAFETY',
    status: 'ASSIGNED',
    detectedAt: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    slaDeadline: new Date(Date.now() + 10 * 3600 * 1000).toISOString(), // 24h SLA
    slaHours: 24,
    isEscalated: false,
    latitude: 19.0661,
    longitude: 72.8692,
    evidencePhotos: [
      {
        id: 'ev-3',
        inspectionId: 'insp-rec-5',
        photoUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f9?w=600&auto=format&fit=crop&q=80',
        caption: 'Faulty emergency contact assembly and worn brake linkage',
        latitude: 19.0661,
        longitude: 72.8692,
        timestamp: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
        inspectorId: 'INSP-MUM-105',
        sha256Hash: 'c1d2e3f4a5b6c7d8e9f0123456789abcdef0123456789abcdef0123456789abc',
        isGeoTagged: true,
        type: 'DEFECT',
      },
    ],
    assignedTo: {
      userId: 'tech-204',
      name: 'Vikram Joshi',
      team: 'Otis Vertical Transit Support',
      assignedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
      deadline: new Date(Date.now() + 10 * 3600 * 1000).toISOString(),
    },
    correctiveAction: {
      id: 'ca-3',
      defectId: 'def-3',
      defectCode: 'DEF-2026-003',
      status: 'ASSIGNED',
      assignedToName: 'Vikram Joshi',
      assignedTeam: 'Otis Vertical Transit Support',
      assignedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
      deadline: new Date(Date.now() + 10 * 3600 * 1000).toISOString(),
      actionPlan: 'Barricade ESC-03, replace contact micro-switch sensor, overhaul brake shoe calipers, and conduct 20-cycle load trip verification.',
      workLogs: [
        {
          timestamp: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
          author: 'Priya Sharma',
          note: 'Escalator barricaded. Safety tape applied. Vendor dispatched.',
        },
      ],
      beforePhotoUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f9?w=600&auto=format&fit=crop&q=80',
    },
  },
  {
    id: 'def-4',
    code: 'DEF-2026-004',
    inspectionId: 'insp-rec-2',
    siteId: 'site-2',
    siteName: 'National Highway Overpass 44 Viaduct',
    inspectorId: 'INSP-DEL-102',
    inspectorName: 'Amit Patel',
    title: 'Expansion Joint Rubber Bellow Displacement & Debris Clogging',
    description: 'Expansion gap between Pier 8 and 9 has 30% displaced neoprene seal. Heavy gravel accumulated in recess, inhibiting thermal movement.',
    severity: 'MEDIUM',
    category: 'CIVIL',
    status: 'PENDING_VERIFICATION',
    detectedAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    slaDeadline: new Date(Date.now() + 24 * 3600 * 1000).toISOString(), // 72h SLA
    slaHours: 72,
    isEscalated: false,
    latitude: 28.5358,
    longitude: 77.3912,
    evidencePhotos: [
      {
        id: 'ev-4',
        inspectionId: 'insp-rec-2',
        photoUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&auto=format&fit=crop&q=80',
        caption: 'Clogged neoprene joint before clearing',
        latitude: 28.5358,
        longitude: 77.3912,
        timestamp: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
        inspectorId: 'INSP-DEL-102',
        sha256Hash: '9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b',
        isGeoTagged: true,
        type: 'BEFORE_CORRECTIVE',
      },
    ],
    assignedTo: {
      userId: 'cont-09',
      name: 'NHAI Maintenance Cell 4',
      team: 'Highway Surface Crew',
      assignedAt: new Date(Date.now() - 40 * 3600 * 1000).toISOString(),
      deadline: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
    },
    correctiveAction: {
      id: 'ca-4',
      defectId: 'def-4',
      defectCode: 'DEF-2026-004',
      status: 'PENDING_VERIFICATION',
      assignedToName: 'NHAI Maintenance Cell 4',
      assignedTeam: 'Highway Surface Crew',
      assignedAt: new Date(Date.now() - 40 * 3600 * 1000).toISOString(),
      deadline: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
      actionPlan: 'High-pressure air jet flush of expansion chamber, reset elastomeric seal with polyurethane mastic anchor.',
      workLogs: [
        {
          timestamp: new Date(Date.now() - 30 * 3600 * 1000).toISOString(),
          author: 'Foreman Rakesh',
          note: 'Debris flushed out completely. 15kg aggregate extracted.',
        },
        {
          timestamp: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
          author: 'Foreman Rakesh',
          note: 'New neoprene strip vulcanized and sealed into place. Ready for supervisor inspection.',
        },
      ],
      beforePhotoUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&auto=format&fit=crop&q=80',
      afterPhotoUrl: 'https://images.unsplash.com/photo-1517581177682-a085bb7ffb15?w=600&auto=format&fit=crop&q=80',
      verificationNotes: 'Joint flush inspected. Seal aligned smoothly across span with 25mm expansion margin confirmed.',
    },
  },
  {
    id: 'def-5',
    code: 'DEF-2026-005',
    inspectionId: 'insp-rec-4',
    siteId: 'site-4',
    siteName: 'Green Valley Water Treatment Plant',
    inspectorId: 'INSP-PUN-104',
    inspectorName: 'Manoj Joshi',
    title: 'Effluent Clarifier Basin 1 Overflow Weirs Algae Build-Up',
    description: 'Minor green algae buildup on peripheral V-notch weirs causing slight hydraulic unevenness.',
    severity: 'LOW',
    category: 'ENVIRONMENTAL',
    status: 'CLOSED',
    detectedAt: new Date(Date.now() - 120 * 3600 * 1000).toISOString(),
    slaDeadline: new Date(Date.now() + 48 * 3600 * 1000).toISOString(), // 7 days SLA
    slaHours: 168,
    isEscalated: false,
    latitude: 18.4389,
    longitude: 73.7634,
    evidencePhotos: [
      {
        id: 'ev-5',
        inspectionId: 'insp-rec-4',
        photoUrl: 'https://images.unsplash.com/photo-1574482620811-1aa16fed3bf8?w=600&auto=format&fit=crop&q=80',
        caption: 'Algae formation along weir plates',
        latitude: 18.4389,
        longitude: 73.7634,
        timestamp: new Date(Date.now() - 120 * 3600 * 1000).toISOString(),
        inspectorId: 'INSP-PUN-104',
        sha256Hash: '11223344556677889900aabbccddeeff11223344556677889900aabbccddeeff',
        isGeoTagged: true,
        type: 'BEFORE_CORRECTIVE',
      },
    ],
    assignedTo: {
      userId: 'san-01',
      name: 'Sanitation Team B',
      team: 'Water Works Facility Operations',
      assignedAt: new Date(Date.now() - 110 * 3600 * 1000).toISOString(),
      deadline: new Date(Date.now() + 50 * 3600 * 1000).toISOString(),
    },
    correctiveAction: {
      id: 'ca-5',
      defectId: 'def-5',
      defectCode: 'DEF-2026-005',
      status: 'CLOSED',
      assignedToName: 'Sanitation Team B',
      assignedTeam: 'Water Works Facility Operations',
      assignedAt: new Date(Date.now() - 110 * 3600 * 1000).toISOString(),
      deadline: new Date(Date.now() + 50 * 3600 * 1000).toISOString(),
      actionPlan: 'Mechanical scraping with non-metallic blades followed by mild chlorine bio-wash.',
      workLogs: [
        {
          timestamp: new Date(Date.now() - 90 * 3600 * 1000).toISOString(),
          author: 'Team Lead Verma',
          note: 'Clarifier weirs brushed clean and rinsed thoroughly.',
        },
      ],
      beforePhotoUrl: 'https://images.unsplash.com/photo-1574482620811-1aa16fed3bf8?w=600&auto=format&fit=crop&q=80',
      afterPhotoUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&auto=format&fit=crop&q=80',
      verificationNotes: 'Supervisor verified: Weir edges spotless, uniform laminar flow restored across 360 degrees.',
      verifiedBy: 'Priya Sharma (Supervisor)',
      verifiedAt: new Date(Date.now() - 40 * 3600 * 1000).toISOString(),
      closedAt: new Date(Date.now() - 38 * 3600 * 1000).toISOString(),
    },
  },
];

export const DEMO_CHECKLIST_TEMPLATE = [
  {
    id: 'chk-1',
    category: 'Structural Integrity',
    question: 'Are concrete piers, beams, and slabs free from visible shear/flexure cracks or spalling?',
    status: 'FAIL' as const,
    remarks: 'Critical crack detected on Pier P-14 cantilever support arm.',
    isMandatory: true,
    requiresPhotoOnFail: true,
  },
  {
    id: 'chk-2',
    category: 'Structural Integrity',
    question: 'Are structural joints, bearing pads, and seismic restrainers in specified alignment?',
    status: 'PASS' as const,
    remarks: 'Bearing elastomeric pads seated properly with no tilt.',
    isMandatory: true,
    requiresPhotoOnFail: true,
  },
  {
    id: 'chk-3',
    category: 'Electrical & Grounding',
    question: 'Are high-voltage conduits, grounding pits, and lightning arrestors within nominal specs (<1 Ohm)?',
    status: 'PASS' as const,
    remarks: 'Ground continuity verified across spans.',
    isMandatory: true,
    requiresPhotoOnFail: true,
  },
  {
    id: 'chk-4',
    category: 'Occupational Safety',
    question: 'Are perimeter fall-arrest barricades, edge nettings, and warning signage securely anchored?',
    status: 'PASS' as const,
    remarks: 'All safety nettings tested for 250kg tensile resistance.',
    isMandatory: true,
    requiresPhotoOnFail: false,
  },
  {
    id: 'chk-5',
    category: 'Drainage & Environmental',
    question: 'Are drainage spouts, weep holes, and catch-basins free of siltation blockage?',
    status: 'PASS' as const,
    remarks: 'Stormwater channels clear with positive gradient.',
    isMandatory: false,
    requiresPhotoOnFail: false,
  },
];

export const DEMO_INSPECTIONS: Inspection[] = [
  {
    id: 'insp-rec-1',
    inspectionNumber: 'INSP-2026-0089',
    siteId: 'site-1',
    siteName: 'Metro Corridor Phase 2 - Elevated Viaduct',
    siteCode: 'SITE-BLR-METRO-02',
    inspectorId: 'INSP-BLR-101',
    inspectorName: 'Rajesh Kumar',
    status: 'IN_PROGRESS',
    startedAt: new Date(Date.now() - 11 * 3600 * 1000).toISOString(),
    startLatitude: 12.9756,
    startLongitude: 77.6094,
    isGeofenceVerified: true,
    distanceFromSiteMeters: 45,
    checklists: DEMO_CHECKLIST_TEMPLATE,
    defectsCount: 1,
    criticalCount: 1,
    highCount: 0,
    score: 68,
    overallRemarks: 'Detailed pier examination ongoing. High risk shear fault flagged for rapid engineering intervention.',
    evidence: [
      {
        id: 'ev-1',
        inspectionId: 'insp-rec-1',
        photoUrl: 'https://images.unsplash.com/photo-1590069261209-f8e9b8642343?w=600&auto=format&fit=crop&q=80',
        caption: 'Cantilever arm shear crack with exposed rebar at pier P-14',
        latitude: 12.9758,
        longitude: 77.6091,
        timestamp: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
        inspectorId: 'INSP-BLR-101',
        sha256Hash: 'a8b94f1c93847e19da82137bc89d41289fe9432ab127d498302bf784a9182301',
        isGeoTagged: true,
        type: 'DEFECT',
      },
    ],
    isSynced: true,
    syncTimestamp: new Date(Date.now() - 9 * 3600 * 1000).toISOString(),
  },
  {
    id: 'insp-rec-2',
    inspectionNumber: 'INSP-2026-0088',
    siteId: 'site-2',
    siteName: 'National Highway Overpass 44 Viaduct',
    siteCode: 'SITE-NCR-NH44-FLY',
    inspectorId: 'INSP-DEL-102',
    inspectorName: 'Amit Patel',
    status: 'COMPLETED',
    startedAt: new Date(Date.now() - 50 * 3600 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 47 * 3600 * 1000).toISOString(),
    startLatitude: 28.5355,
    startLongitude: 77.391,
    endLatitude: 28.536,
    endLongitude: 77.3915,
    isGeofenceVerified: true,
    distanceFromSiteMeters: 60,
    checklists: [
      {
        id: 'chk-21',
        category: 'Highway Pavement',
        question: 'Is asphalt wearing course free from rutting > 10mm?',
        status: 'PASS',
        isMandatory: true,
        requiresPhotoOnFail: true,
      },
      {
        id: 'chk-22',
        category: 'Expansion Joint',
        question: 'Are expansion joint gaps clean and elastomeric seals intact?',
        status: 'FAIL',
        remarks: 'Joint clogged at Pier 8-9 with gravel.',
        isMandatory: true,
        requiresPhotoOnFail: true,
      },
      {
        id: 'chk-23',
        category: 'Crash Barriers',
        question: 'Are W-beam crash barriers and retro-reflective studs bolted tightly?',
        status: 'PASS',
        isMandatory: true,
        requiresPhotoOnFail: false,
      },
    ],
    defectsCount: 1,
    criticalCount: 0,
    highCount: 0,
    score: 84,
    overallRemarks: 'Viaduct superstructure is structurally sound. Corrective action underway for expansion joint clearing.',
    evidence: [],
    isSynced: true,
    syncTimestamp: new Date(Date.now() - 46 * 3600 * 1000).toISOString(),
  },
  {
    id: 'insp-rec-3',
    inspectionNumber: 'INSP-2026-0087',
    siteId: 'site-3',
    siteName: 'High Voltage Tech Park Substation 220kV',
    siteCode: 'SITE-HYD-TECH-ELEC',
    inspectorId: 'INSP-HYD-103',
    inspectorName: 'Sneha Reddy',
    status: 'COMPLETED',
    startedAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    startLatitude: 17.4435,
    startLongitude: 78.3772,
    endLatitude: 17.4438,
    endLongitude: 78.3774,
    isGeofenceVerified: true,
    distanceFromSiteMeters: 30,
    checklists: [
      {
        id: 'chk-31',
        category: 'Transformer Health',
        question: 'Are oil levels, silica gel breather color, and radiator fins leakage-free?',
        status: 'FAIL',
        remarks: 'Active oil drip on radiator 2, silica gel pink saturated.',
        isMandatory: true,
        requiresPhotoOnFail: true,
      },
      {
        id: 'chk-32',
        category: 'Earth Grounding',
        question: 'Does earth resistance measure below 1.0 Ohm across test pits?',
        status: 'FAIL',
        remarks: 'Earth pit 4 measures 8.4 Ohms.',
        isMandatory: true,
        requiresPhotoOnFail: true,
      },
      {
        id: 'chk-33',
        category: 'Busbar Clearance',
        question: 'Are phase-to-phase and phase-to-ground clearances compliant with CEA norms?',
        status: 'PASS',
        isMandatory: true,
        requiresPhotoOnFail: true,
      },
    ],
    defectsCount: 1,
    criticalCount: 1,
    highCount: 0,
    score: 42,
    overallRemarks: 'Urgent shutdown recommended for Bay 2. Electrical hazard escalation triggered.',
    evidence: [],
    isSynced: true,
  },
  {
    id: 'insp-rec-4',
    inspectionNumber: 'INSP-2026-0086',
    siteId: 'site-4',
    siteName: 'Green Valley Water Treatment Plant',
    siteCode: 'SITE-PUN-WATER-TREAT',
    inspectorId: 'INSP-PUN-104',
    inspectorName: 'Manoj Joshi',
    status: 'COMPLETED',
    startedAt: new Date(Date.now() - 124 * 3600 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 120 * 3600 * 1000).toISOString(),
    startLatitude: 18.4386,
    startLongitude: 73.7631,
    endLatitude: 18.4388,
    endLongitude: 73.7633,
    isGeofenceVerified: true,
    distanceFromSiteMeters: 55,
    checklists: [
      {
        id: 'chk-41',
        category: 'Clarifier Operation',
        question: 'Is sludge scrapper torque normal with clean weir overflow?',
        status: 'PASS',
        isMandatory: true,
        requiresPhotoOnFail: false,
      },
      {
        id: 'chk-42',
        category: 'Chlorination Safety',
        question: 'Are chlorine gas leak sensors calibrated with automatic scrubbers on standby?',
        status: 'PASS',
        isMandatory: true,
        requiresPhotoOnFail: true,
      },
    ],
    defectsCount: 1,
    criticalCount: 0,
    highCount: 0,
    score: 91,
    overallRemarks: 'Regular bi-weekly audit completed. Algae issue resolved and verified.',
    evidence: [],
    isSynced: true,
  },
  {
    id: 'insp-rec-5',
    inspectionNumber: 'INSP-2026-0085',
    siteId: 'site-5',
    siteName: 'Smart City Multi-Modal Transit Terminal',
    siteCode: 'SITE-MUM-TRANSIT-HUB',
    inspectorId: 'INSP-MUM-105',
    inspectorName: 'Neha Chawla',
    status: 'COMPLETED',
    startedAt: new Date(Date.now() - 16 * 3600 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 13 * 3600 * 1000).toISOString(),
    startLatitude: 19.0657,
    startLongitude: 72.8688,
    endLatitude: 19.066,
    endLongitude: 72.869,
    isGeofenceVerified: true,
    distanceFromSiteMeters: 70,
    checklists: [
      {
        id: 'chk-51',
        category: 'Passenger Escalators',
        question: 'Do all emergency stopping mechanisms respond within standard deceleration curve?',
        status: 'FAIL',
        remarks: 'ESC-03 emergency trip brake delay > 250ms.',
        isMandatory: true,
        requiresPhotoOnFail: true,
      },
      {
        id: 'chk-52',
        category: 'Fire Evacuation',
        question: 'Are fire doors, illuminated exit signs, and smoke dampers active?',
        status: 'PASS',
        isMandatory: true,
        requiresPhotoOnFail: true,
      },
    ],
    defectsCount: 1,
    criticalCount: 0,
    highCount: 1,
    score: 74,
    overallRemarks: 'Escalator safety interlock needs immediate repair before evening rush hour.',
    evidence: [],
    isSynced: true,
  },
  {
    id: 'insp-rec-6',
    inspectionNumber: 'INSP-2026-0084',
    siteId: 'site-1',
    siteName: 'Metro Corridor Phase 2 - Elevated Viaduct',
    siteCode: 'SITE-BLR-METRO-02',
    inspectorId: 'INSP-BLR-101',
    inspectorName: 'Rajesh Kumar',
    status: 'COMPLETED',
    startedAt: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 14 * 24 * 3600 * 1000 + 7200 * 1000).toISOString(),
    startLatitude: 12.9756,
    startLongitude: 77.6094,
    isGeofenceVerified: true,
    distanceFromSiteMeters: 50,
    checklists: [],
    defectsCount: 0,
    criticalCount: 0,
    highCount: 0,
    score: 95,
    overallRemarks: 'Routine track girder alignment audit. All deflections within permissible limits.',
    evidence: [],
    isSynced: true,
  },
  {
    id: 'insp-rec-7',
    inspectionNumber: 'INSP-2026-0083',
    siteId: 'site-2',
    siteName: 'National Highway Overpass 44 Viaduct',
    siteCode: 'SITE-NCR-NH44-FLY',
    inspectorId: 'INSP-DEL-102',
    inspectorName: 'Amit Patel',
    status: 'COMPLETED',
    startedAt: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 20 * 24 * 3600 * 1000 + 8000 * 1000).toISOString(),
    startLatitude: 28.5355,
    startLongitude: 77.391,
    isGeofenceVerified: true,
    distanceFromSiteMeters: 40,
    checklists: [],
    defectsCount: 0,
    criticalCount: 0,
    highCount: 0,
    score: 97,
    overallRemarks: 'High-speed pavement friction testing completed. Skid resistance index nominal.',
    evidence: [],
    isSynced: true,
  },
  {
    id: 'insp-rec-8',
    inspectionNumber: 'INSP-2026-0082',
    siteId: 'site-3',
    siteName: 'High Voltage Tech Park Substation 220kV',
    siteCode: 'SITE-HYD-TECH-ELEC',
    inspectorId: 'INSP-HYD-103',
    inspectorName: 'Sneha Reddy',
    status: 'COMPLETED',
    startedAt: new Date(Date.now() - 28 * 24 * 3600 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 28 * 24 * 3600 * 1000 + 6400 * 1000).toISOString(),
    startLatitude: 17.4435,
    startLongitude: 78.3772,
    isGeofenceVerified: true,
    distanceFromSiteMeters: 65,
    checklists: [],
    defectsCount: 1,
    criticalCount: 0,
    highCount: 1,
    score: 82,
    overallRemarks: 'Infrared thermography scan detected localized hotspot on SF6 breaker terminal.',
    evidence: [],
    isSynced: true,
  },
  {
    id: 'insp-rec-9',
    inspectionNumber: 'INSP-2026-0081',
    siteId: 'site-4',
    siteName: 'Green Valley Water Treatment Plant',
    siteCode: 'SITE-PUN-WATER-TREAT',
    inspectorId: 'INSP-PUN-104',
    inspectorName: 'Manoj Joshi',
    status: 'COMPLETED',
    startedAt: new Date(Date.now() - 35 * 24 * 3600 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 35 * 24 * 3600 * 1000 + 7000 * 1000).toISOString(),
    startLatitude: 18.4386,
    startLongitude: 73.7631,
    isGeofenceVerified: true,
    distanceFromSiteMeters: 80,
    checklists: [],
    defectsCount: 0,
    criticalCount: 0,
    highCount: 0,
    score: 94,
    overallRemarks: 'Flocculation chamber hydraulic test passed. Zero leakage on underdrains.',
    evidence: [],
    isSynced: true,
  },
  {
    id: 'insp-rec-10',
    inspectionNumber: 'INSP-2026-0080',
    siteId: 'site-5',
    siteName: 'Smart City Multi-Modal Transit Terminal',
    siteCode: 'SITE-MUM-TRANSIT-HUB',
    inspectorId: 'INSP-MUM-105',
    inspectorName: 'Neha Chawla',
    status: 'PENDING',
    startedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    startLatitude: 19.0657,
    startLongitude: 72.8688,
    isGeofenceVerified: false,
    distanceFromSiteMeters: 120,
    checklists: [],
    defectsCount: 0,
    criticalCount: 0,
    highCount: 0,
    score: 0,
    overallRemarks: 'Inspection scheduled for concourse structural roof trusses.',
    evidence: [],
    isSynced: true,
  },
];

export const DEMO_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'CRITICAL DEFECT DETECTED',
    message: 'Pier P-14 cantilever shear crack reported by Rajesh Kumar at Metro Corridor Phase 2.',
    type: 'CRITICAL_ALERT',
    severity: 'CRITICAL',
    timestamp: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
    targetRole: 'SUPERVISOR',
    read: false,
    defectId: 'def-1',
    siteName: 'Metro Corridor Phase 2',
  },
  {
    id: 'notif-2',
    title: 'DIRECTOR SLA ESCALATION',
    message: 'DEF-2026-001 (Pier P-14 Shear Crack) 4-hour critical SLA nearing limit. Auto-escalated to Director.',
    type: 'ESCALATION',
    severity: 'CRITICAL',
    timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    targetRole: 'DIRECTOR',
    read: false,
    defectId: 'def-1',
    siteName: 'Metro Corridor Phase 2',
  },
  {
    id: 'notif-3',
    title: 'HIGH VOLTAGE FLASH HAZARD',
    message: 'Dielectric oil drip and earth pit resistance fault reported at Tech Park Substation 220kV.',
    type: 'CRITICAL_ALERT',
    severity: 'CRITICAL',
    timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    targetRole: 'SUPERVISOR',
    read: false,
    defectId: 'def-2',
    siteName: 'Tech Park Substation 220kV',
  },
  {
    id: 'notif-4',
    title: 'CORRECTIVE ACTION READY FOR VERIFICATION',
    message: 'Foreman Rakesh uploaded after-repair photo for Expansion Joint DEF-2026-004. Approval required.',
    type: 'VERIFICATION_REQUEST',
    severity: 'MEDIUM',
    timestamp: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    targetRole: 'SUPERVISOR',
    read: true,
    defectId: 'def-4',
    siteName: 'National Highway Overpass 44',
  },
];

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    action: 'DEFECT_AUTO_ESCALATION',
    actorId: 'system-sla-daemon',
    actorName: 'Automated SLA Monitor',
    actorRole: 'ADMIN',
    entityType: 'DEFECT',
    entityId: 'def-1',
    details: 'Critical defect DEF-2026-001 escalated to Director Dr. Anand Verma due to elapsed 50% SLA window.',
    ipAddress: '10.240.0.1 (Internal Worker)',
    evidenceHash: 'a8b94f1c93847e19da82137bc89d41289fe9432ab127d498302bf784a9182301',
  },
  {
    id: 'aud-2',
    timestamp: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    action: 'CORRECTIVE_ACTION_ASSIGNED',
    actorId: 'usr-2',
    actorName: 'Priya Sharma',
    actorRole: 'SUPERVISOR',
    entityType: 'CORRECTIVE_ACTION',
    entityId: 'ca-1',
    details: 'Assigned Heavy Civil Rapid Response Unit (Lead Suresh Patil) with 4-hour turnaround directive.',
    ipAddress: '49.206.14.82',
  },
  {
    id: 'aud-3',
    timestamp: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
    action: 'EVIDENCE_CRYPTO_SEALED',
    actorId: 'INSP-BLR-101',
    actorName: 'Rajesh Kumar',
    actorRole: 'INSPECTOR',
    entityType: 'EVIDENCE',
    entityId: 'ev-1',
    details: 'Photo evidence anchored with GPS (12.9758, 77.6091), geofenced verified (45m radius), tamper hash stamped.',
    ipAddress: '157.48.21.99',
    evidenceHash: 'a8b94f1c93847e19da82137bc89d41289fe9432ab127d498302bf784a9182301',
  },
  {
    id: 'aud-4',
    timestamp: new Date(Date.now() - 11 * 3600 * 1000).toISOString(),
    action: 'INSPECTION_START_GEOFENCE_VALIDATED',
    actorId: 'INSP-BLR-101',
    actorName: 'Rajesh Kumar',
    actorRole: 'INSPECTOR',
    entityType: 'INSPECTION',
    entityId: 'insp-rec-1',
    details: 'Inspection started at Site SITE-BLR-METRO-02. Distance to perimeter: 45m (Permissible: 300m). Passed geofence.',
    ipAddress: '157.48.21.99',
  },
  {
    id: 'aud-5',
    timestamp: new Date(Date.now() - 40 * 3600 * 1000).toISOString(),
    action: 'CORRECTIVE_ACTION_VERIFIED_CLOSED',
    actorId: 'usr-2',
    actorName: 'Priya Sharma',
    actorRole: 'SUPERVISOR',
    entityType: 'CORRECTIVE_ACTION',
    entityId: 'ca-5',
    details: 'Before/after photographic audit reviewed. Algae buildup cleared to standard. Defect closed.',
    ipAddress: '49.206.14.82',
    evidenceHash: '11223344556677889900aabbccddeeff11223344556677889900aabbccddeeff',
  },
];

// Base Paper Area 3: IoT and Real-Time Sensor Telemetry
export const DEMO_IOT_SENSORS: IoTSensorNode[] = [
  {
    id: 'iot-1',
    siteId: 'site-1',
    siteName: 'Silk Board Multi-Level Flyover',
    code: 'IOT-VIB-01',
    type: 'VIBRATION',
    name: 'Pier P-14 Tri-Axial Accelerometer',
    currentValue: 4.82,
    unit: 'mm/s²',
    thresholdMin: 0.5,
    thresholdMax: 3.5,
    status: 'CRITICAL',
    batteryLevel: 91,
    lastPing: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    history: [
      { timestamp: '10:00', value: 2.1 },
      { timestamp: '10:15', value: 2.4 },
      { timestamp: '10:30', value: 3.1 },
      { timestamp: '10:45', value: 3.6 },
      { timestamp: '11:00', value: 4.82 },
    ],
  },
  {
    id: 'iot-2',
    siteId: 'site-1',
    siteName: 'Silk Board Multi-Level Flyover',
    code: 'IOT-CRK-02',
    type: 'CRACK_DISPLACEMENT',
    name: 'Girder Span G-4 Crack Sensor',
    currentValue: 2.85,
    unit: 'mm',
    thresholdMin: 0.1,
    thresholdMax: 2.0,
    status: 'WARNING',
    batteryLevel: 84,
    lastPing: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    history: [
      { timestamp: '10:00', value: 1.8 },
      { timestamp: '10:15', value: 1.9 },
      { timestamp: '10:30', value: 2.1 },
      { timestamp: '10:45', value: 2.5 },
      { timestamp: '11:00', value: 2.85 },
    ],
  },
  {
    id: 'iot-3',
    siteId: 'site-2',
    siteName: 'Namma Metro Yellow Line Exp',
    code: 'IOT-TLT-01',
    type: 'STRUCTURAL_TILT',
    name: 'Pier P-88 Dual-Axis Inclinometer',
    currentValue: 0.42,
    unit: 'deg',
    thresholdMin: -0.5,
    thresholdMax: 0.5,
    status: 'NORMAL',
    batteryLevel: 96,
    lastPing: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    history: [
      { timestamp: '10:00', value: 0.38 },
      { timestamp: '10:15', value: 0.40 },
      { timestamp: '10:30', value: 0.41 },
      { timestamp: '10:45', value: 0.42 },
      { timestamp: '11:00', value: 0.42 },
    ],
  },
  {
    id: 'iot-4',
    siteId: 'site-3',
    siteName: 'Nandi Hills Expressway Bridge',
    code: 'IOT-STR-01',
    type: 'STRAIN_GAUGE',
    name: 'Abutment A-1 Fiber-Bragg Strain Sensor',
    currentValue: 345,
    unit: 'με',
    thresholdMin: 50,
    thresholdMax: 500,
    status: 'NORMAL',
    batteryLevel: 88,
    lastPing: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    history: [
      { timestamp: '10:00', value: 310 },
      { timestamp: '10:15', value: 325 },
      { timestamp: '10:30', value: 340 },
      { timestamp: '10:45', value: 342 },
      { timestamp: '11:00', value: 345 },
    ],
  },
  {
    id: 'iot-5',
    siteId: 'site-4',
    siteName: 'Kaveri Water Pipeline Corridor',
    code: 'IOT-COR-01',
    type: 'HUMIDITY_CORROSION',
    name: 'Joint Valve J-22 Electrochemical Probe',
    currentValue: 88.5,
    unit: '% RH',
    thresholdMin: 20,
    thresholdMax: 75,
    status: 'WARNING',
    batteryLevel: 79,
    lastPing: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    history: [
      { timestamp: '10:00', value: 72.0 },
      { timestamp: '10:15', value: 76.5 },
      { timestamp: '10:30', value: 81.2 },
      { timestamp: '10:45', value: 85.0 },
      { timestamp: '11:00', value: 88.5 },
    ],
  },
];

// Base Paper Area 5: Decision Support Recommendations
export const DEMO_DECISION_SUPPORT: DecisionSupportItem[] = [
  {
    id: 'dec-1',
    siteId: 'site-1',
    siteName: 'Silk Board Multi-Level Flyover',
    defectId: 'def-1',
    defectCode: 'DEF-BLR-001',
    riskScore: 94,
    urgencyLevel: 'IMMEDIATE',
    title: 'High-Shear Reinforcement & Structural Jacket Directive',
    diagnosis: 'AI Computer Vision detected 4.2mm structural diagonal shear crack at Pier P-14 with IoT vibration spike (4.82 mm/s²). Risk of progressive fatigue failure under peak peak-hour transit load.',
    recommendedAction: 'Immediate temporary lane diversion of left carriageway, followed by carbon-fiber polymer (CFRP) pressure injection and structural steel jacket bolting within 4 hours.',
    estimatedCostInINR: '₹ 3,45,000',
    requiredTeam: 'Heavy Civil Rapid Structural Response Unit',
    targetSLADays: 1,
    status: 'APPROVED',
    rationale: 'Exceeds IRC:SP:40 safety limits. Vibrational harmonic correlation confirms structural movement.',
  },
  {
    id: 'dec-2',
    siteId: 'site-2',
    siteName: 'Namma Metro Yellow Line Exp',
    defectId: 'def-2',
    defectCode: 'DEF-BLR-002',
    riskScore: 82,
    urgencyLevel: 'HIGH_PRIORITY',
    title: 'Electrochemical Passivation & Concrete Re-Profiling',
    diagnosis: 'Concrete cover spall of 450mm length with exposed deformed reinforcement bars undergoing aggressive oxidation.',
    recommendedAction: 'Abrasive grit blasting of oxidized rust, zinc-rich anti-corrosion primer application, and high-strength polymer-modified mortar rebuilding.',
    estimatedCostInINR: '₹ 1,20,000',
    requiredTeam: 'Specialized Concrete Remediation Crew',
    targetSLADays: 2,
    status: 'PENDING_DECISION',
    rationale: 'Direct moisture ingress will accelerate rebar cross-section loss by 12% per quarter if untreated.',
  },
  {
    id: 'dec-3',
    siteId: 'site-3',
    siteName: 'Nandi Hills Expressway Bridge',
    defectId: 'def-3',
    defectCode: 'DEF-BLR-003',
    riskScore: 68,
    urgencyLevel: 'SCHEDULED',
    title: 'Elastomeric Bearing Reseating & Jacking',
    diagnosis: 'Shear deformation of 22mm on western bearing pad exceeding manufacturer shear strain tolerance by 14%.',
    recommendedAction: 'Hydraulic jacking of girder span during midnight non-traffic window and bearing pad replacement with neoprene steel-laminated pad.',
    estimatedCostInINR: '₹ 4,80,000',
    requiredTeam: 'Bridge Engineering & Hydraulic Lifting Unit',
    targetSLADays: 7,
    status: 'PENDING_DECISION',
    rationale: 'Thermal expansion during summer months will generate unmitigated lateral thrust on pier cap.',
  },
  {
    id: 'dec-4',
    siteId: 'site-4',
    siteName: 'Kaveri Water Pipeline Corridor',
    defectId: 'def-4',
    defectCode: 'DEF-BLR-004',
    riskScore: 52,
    urgencyLevel: 'MONITOR',
    title: 'Cathodic Sacrificial Anode Installation',
    diagnosis: 'Surface galvanic corrosion on pipeline collar ring with soil resistivity test showing high salinity conductivity.',
    recommendedAction: 'Install magnesium sacrificial ribbon anode bed and apply high-build coal-tar polyurethane coating.',
    estimatedCostInINR: '₹ 85,000',
    requiredTeam: 'Pipeline & Cathodic Protection Cell',
    targetSLADays: 14,
    status: 'APPROVED',
    rationale: 'Preventive mitigation prevents water main pressure blowout during peak summer pumping.',
  },
];

// Management Flow: Generated Reports
export const DEMO_REPORTS: InspectionReportSummary[] = [
  {
    id: 'rep-001',
    reportNumber: 'SIH-AUD-2026-001',
    title: 'Structural Safety & Quality Certification Audit',
    siteId: 'site-1',
    siteName: 'Silk Board Multi-Level Flyover',
    inspectorName: 'Rajesh Kumar (INSP-BLR-101)',
    generatedDate: '2026-09-09',
    inspectionDate: '2026-09-09 09:30 AM',
    overallScore: 68,
    status: 'FLAGGED',
    geofenceVerified: true,
    gpsCoordinates: { lat: 12.9172, lng: 77.6228 },
    evidenceCount: 6,
    criticalDefects: 1,
    highDefects: 1,
    summaryRemarks: 'Pier P-14 shear crack flagged for urgent remediation. Geofence and cryptographic SHA-256 evidence validated.',
  },
  {
    id: 'rep-002',
    reportNumber: 'SIH-AUD-2026-002',
    title: 'Metro Viaduct Quarterly Compliance Audit',
    siteId: 'site-2',
    siteName: 'Namma Metro Yellow Line Exp',
    inspectorName: 'Rajesh Kumar (INSP-BLR-101)',
    generatedDate: '2026-09-08',
    inspectionDate: '2026-09-08 14:15 PM',
    overallScore: 84,
    status: 'COMPLIANT',
    geofenceVerified: true,
    gpsCoordinates: { lat: 12.9352, lng: 77.6101 },
    evidenceCount: 4,
    criticalDefects: 0,
    highDefects: 1,
    summaryRemarks: 'Minor rebar corrosion noted at Pier P-88. Structural deflection within RDSO permissible limits.',
  },
  {
    id: 'rep-003',
    reportNumber: 'SIH-AUD-2026-003',
    title: 'Expressway Abutment & Bearing Inspection',
    siteId: 'site-3',
    siteName: 'Nandi Hills Expressway Bridge',
    inspectorName: 'Sneha Patel (INSP-DEL-204)',
    generatedDate: '2026-09-07',
    inspectionDate: '2026-09-07 11:00 AM',
    overallScore: 78,
    status: 'COMPLIANT',
    geofenceVerified: true,
    gpsCoordinates: { lat: 13.3702, lng: 77.6835 },
    evidenceCount: 5,
    criticalDefects: 0,
    highDefects: 1,
    summaryRemarks: 'Elastomeric bearing pad replacement scheduled. Abutment foundation stable with zero settlement.',
  },
  {
    id: 'rep-004',
    reportNumber: 'SIH-AUD-2026-004',
    title: 'Hydraulic Pipeline Integrity & Pressure Audit',
    siteId: 'site-4',
    siteName: 'Kaveri Water Pipeline Corridor',
    inspectorName: 'Amit Joshi (INSP-MUM-309)',
    generatedDate: '2026-09-06',
    inspectionDate: '2026-09-06 16:40 PM',
    overallScore: 91,
    status: 'COMPLIANT',
    geofenceVerified: true,
    gpsCoordinates: { lat: 12.8715, lng: 77.5648 },
    evidenceCount: 3,
    criticalDefects: 0,
    highDefects: 0,
    summaryRemarks: 'Joint valve collars sealed. Cathodic protection active. All checklist categories passed.',
  },
];
